### ISSUE TITLE
Error installing document_webdav_fast

### ISSUE THREAD

**Issue by diassynthesis** [initOS/openerp-dav#1]
Hi;

I'm getting the following error when trying to install **document_webdav_fast**:

----------Error begin-----

2014-05-31 07:30:14,031 15923 INFO DevDB openerp.modules.loading: module document_webdav_fast: loading webdav_view.xml
2014-05-31 07:30:14,818 15923 INFO DevDB openerp.modules.loading: module document_webdav_fast: loading webdav_setup.xml
2014-05-31 07:30:14,861 15923 ERROR DevDB openerp.tools.convert: Parse error in /usr/lib/pymodules/python2.7/openerp/addons/document_webdav_fast/webdav_setup.xml:11

```
         < record id="document_directory_principals0" model="document.directory">
                        <field name="domain">[]</field>
                        <field eval="1" name="resource_find_all"/>
                        <field eval="0" name="ressource_tree"/>
                        <field name="user_id" eval="False"/>
                         <field name="company_id" ref="base.main_company"/>
                        <field name="type">directory</field>
                        <field eval="[(6,0,[])]" name="group_ids"/>
                       <field name="name">principals</field>
         </record>
        Traceback (most recent call last):
        File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 852, in parse
       self._tags[rec.tag](self.cr, rec, n)
       File "/usr/lib/pymodules/python2.7/openerp/tools/convert.py", line 819, in      _tag_record
       id = self.pool.get('ir.model.data')._update(cr, self.uid, rec_model,   self.module,      res, rec_id or False, not self.isnoupdate(data_node),    noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
      File "/usr/lib/pymodules/python2.7/openerp/addons/base/ir/ir_model.py", line 971, in _update
      res_id = model_obj.create(cr, uid, values, context=context)
       File "/usr/lib/pymodules/python2.7/openerp/addons/document/document.py", line   353, in create
      raise osv.except_osv(_('ValidateError'), _('Directory name must be unique!'))
        except_osv: (u'Erreur de validation', u'Le nom du r\xe9pertoire doit \xeatre unique!')
        2014-05-31 07:30:14,922 15923 ERROR DevDB openerp.netsvc: Erreur de validation
        Le nom du répertoire doit être unique!
```

-----------Error End------

This is related to the directory named **principals** which already exist.
I think, i will get this error also with the following directories: **(  _uids_ , resources, users  and  groups)** , which already exists. (cause i've the module **document_webdav** already installed).

So, my question is: Can we have the module **document_webdav_fast** installed allong with the **document_webdav** module ?

If not, when uninstalling **document_webdav**, what about the others modules (if any) which depends on it ?

Why not propose merging **document_webdav_fast** in OpenERP addons (and replacing the old **document_webdav**?

Or, why not changing the code, and  use the existing directories (if those directories already exist) ?

Best regards.

**Comment by tremlin** [comment]
Thanks for your bug report.
1. document_webdav and document_webdav_fast are mutually exclusive, so only one of both can be installed (document_webdav_fast is a patched copy of document_webdav)
2. To the best of our knowledge there are no public modules that depend on document_webdav. You can check for yourself by running
   `SELECT * FROM ir_module_module_dependency WHERE name = 'document_webdav';`
   against your database.
3. The API of document_webdav and document_webdav_fast is fully interchangeable, so you could easily change the other carddav modules in this repository so that they run with document_webdav. The performance, however, will be remain poor.
4. We already proposed to merge our changes into the main branch (cf. https://code.launchpad.net/~initos.com/openobject-addons/7.0-715444-webdav-performance-improvement/+merge/200288). However, the document_webdav module is no longer of interest for OpenERP/Odoo S.A. and it is removed for the soon released version 8.0. Thus it is unlikely that this merge request will be successful.

**Comment by diassynthesis** [comment]
Thank you, for the response and the explanation.

Best regards.

**Comment by mathi123** [comment]
Does anybody know WHY OpenERP/Odoo is dropping Webdav support?
What is the alternative?

**Comment by tremlin** [comment]
I am not involved with the Odoo core team, so I don't know the exact reasons. But I suspect that it was too hard to migrate the code to the new underlying HTTP server structure of v8 and because documen_webdav was a bit buggy anyway. I am not aware of any alternatives for v8 (or v7 for that matter).

**Comment by mathi123** [comment]
Thanks for the response.
I think its a shame. The latest v7 also doesn't support Webdav anymore (nor document_webdav_fast),
can you confirm this? 
(same bug as here: https://www.odoo.com/forum/help-1/question/how-to-install-webdav-58013 )

Does initOS have any intentions of migrating the module for v8?

Kind regards

**Comment by tremlin** [comment]
Do you a specific error message with document_webdav_fast and v7? We are running Odoo v7 from git (perhaps one week old) together with document_webdav_fast.

At the moment we have no plans to migrate the module to v8, but if there is sufficient demand we may have a look at it.

**Comment by diassynthesis** [comment]
5 years after .... the rest of the story !!!
I know V7.0 is far behind us, but I'm stuck on version 7.0




There is a dependency from knowledge addon module to document_webdav module.
As shown on the attached video when we try to check the box Share repositories (WebDAV) this will try to install the document_webdav module, and in case where document_webdav_fast is already installed an error will be raised.
There are two solutions to this problem:

1. to change the name of the document_webdav_fast module to document_webdav and of course deleting the original document_webdav module from the addon folder.

2. to change all the references to document_webdav in the knowledge module files (res_config.py and res_config_view.xml) to document_webdav_fast.

**Comment by diassynthesis** [comment]
5 years after .... the rest of the story !!!
I know V7.0 is far behind us, but I'm stuck on version 7.0
[document_webdav.zip](https://github.com/initOS/openerp-dav/files/2943390/document_webdav.zip)


There is a dependency from knowledge addon module to document_webdav module.
As shown on the attached video when we try to check the box Share repositories (WebDAV) this will try to install the document_webdav module, and in case where document_webdav_fast is already installed an error will be raised.
There are two solutions to this problem:

1. to change the name of the document_webdav_fast module to document_webdav and of course deleting the original document_webdav module from the addon folder.

2. to change all the references to document_webdav in the knowledge module files (res_config.py and res_config_view.xml) to document_webdav_fast.
