### ISSUE TITLE
Installation/usage issue

### ISSUE THREAD

**Issue by npiganeau** [initOS/openerp-dav#2]
Hello,
I am trying to install and test document_carddav module.
So I installed the module and its dependencies. It seems that there is no problem with that.
But when I try to test the connection by entering the /webdav/$db_name/addressbooks/users/$login/a/m-res.partner/default/ url in a browser, I get prompted for a username and password and then nothing happens.

When I look into the logs, I get:

```
2014-08-29 12:57:41,640 7283 INFO ? openerp.service.http_server: Found user="admin", passwd="***" for db="test-08-23"
2014-08-29 12:57:41,689 7283 INFO test-08-23 werkzeug: 127.0.0.1 - - [29/Aug/2014 12:57:41] "GET /webdav/test-08-23/addressbooks/users/admin/a/m-res.partner/default HTTP/1.1" 500 -
```

So I understand that the credentials are accepted but then I get a 500 error code.

What am I missing ?

Thanks

Nicolas

**Comment by intero-chz** [comment]
Hi, has your browser WebDav or CardDav plugins? Or just use a CardDav Client. So far it is working for me fine with KDE KAddressbook.

**Comment by tremlin** [comment]
OpenERP unfortunately does not log the cause for the HTTP 500 Code. You can try the following patch to trace the cause https://gist.github.com/tremlin/78f7a4ddc327829d1779

**Comment by npiganeau** [comment]
@intero-chz I tried with Chrome, Firefox and with android Carddav-sync and I get the same result each time
I applied the patch from @tremlin (Thanks!), and here the error I get on the log. I don't really understand it. Is it a kind of missing dependency ?

```
2014-09-05 07:04:07,395 9425 INFO ? werkzeug: 127.0.0.1 - - [05/Sep/2014 07:04:07] "PROPFIND /webdav/labadis/addressbooks/users/admin/a/m-res.partner/default/ HTTP/1.1" 401 -
2014-09-05 07:04:07,901 9425 INFO ? openerp.service.http_server: Found user="admin", passwd="***" for db="labadis"
2014-09-05 07:04:07,944 9425 ERROR labadis openerp.service.wsgi_server: DAVHandler instance has no attribute '_BufferedHTTPRequestHandler__buffer'
Traceback (most recent call last):
File "/usr/lib/pymodules/python2.7/openerp/service/wsgi_server.py", line 343, in wsgi_handler
  method()
File "/usr/lib/python2.7/dist-packages/DAV/WebDAVServer.py", line 344, in do_PROPFIND
  self.send_body_chunks_if_http11(DATA, '207','Multi-Status','Multiple responses')
File "/usr/lib/python2.7/dist-packages/DAV/WebDAVServer.py", line 134, in send_body_chunks_if_http11
  self.send_body(DATA, code, msg, desc, ctype, headers)
File "/usr/local/src/openerp-addons/document_webdav_fast/webdav_server.py", line 209, in send_body
  ctype=ctype, headers=headers)
File "/usr/lib/python2.7/dist-packages/DAV/WebDAVServer.py", line 78, in send_body
  self.send_response(code,message=msg)
File "/usr/local/src/openerp-addons/document_webdav_fast/webdav_server.py", line 188, in send_response
  BaseHTTPRequestHandler.send_response(self, int(code), message)
File "/usr/lib/python2.7/BaseHTTPServer.py", line 395, in send_response
  self.send_header('Server', self.version_string())
File "/usr/local/src/openerp-addons/document_webdav_fast/webdav_server.py", line 193, in send_header
  DAVRequestHandler.send_header(self, key, value)
File "/usr/lib/python2.7/dist-packages/DAV/BufferingHTTPServer.py", line 78, in send_header
  self._append("%s: %s\r\n" % (keyword, value))
File "/usr/lib/python2.7/dist-packages/DAV/BufferingHTTPServer.py", line 60, in _append
  self.__buffer=self.__buffer+s
AttributeError: DAVHandler instance has no attribute '_BufferedHTTPRequestHandler__buffer'
2014-09-05 07:04:07,944 9425 INFO labadis werkzeug: 127.0.0.1 - - [05/Sep/2014 07:04:07] "PROPFIND /webdav/labadis/addressbooks/users/admin/a/m-res.partner/default/  HTTP/1.1" 500 -
```

**Comment by tremlin** [comment]
@npiganeau you could try to upgrade your Python WebDAV library to 0.9.8 https://pypi.python.org/pypi/PyWebDAV

**Comment by npiganeau** [comment]
@tremlin That was the issue, thanks ! I now know I should have read the Readme file completely !
